### ISSUE TITLE
Short multi-character arguments do not work.

### ISSUE THREAD

**Issue by kyegupov** [isaacs/jackspeak#1]
TAP documentation (used as an example in this package) suggests you can use `-no-cov` instead of `--no-coverage`.
Actually, the code does not support `-cov` or `-no-cov` (with single hyphen)
Only single-character short arguments are accepted by https://github.com/isaacs/jackspeak/blob/master/index.js#L539-L564

**Comment by kyegupov** [comment]
and `--cov` / `--no-cov` are supported (accidentally?) by https://github.com/isaacs/jackspeak/blob/master/index.js#L572-L574

**Comment by isaacs** [comment]
Yeah, that's definitely a case where this parser is not as strict as it intends to be.  A single `-` should only be valid for single-character options, but tap historically supported `-no-cov`. Really, the `short` field should be restricted to be a single character, and tap should define `cov: flag({ alias: '--coverage', hidden: true }), 'no-cov': flag({ alias: '--no-coverage', hidden: true })` instead of setting `cov` as a short opt.

**Comment by isaacs** [comment]
No longer relevant as of v2.  Short options must be single-character now.
