### ISSUE TITLE
Manifest Confusion - Reported Dependencies do not match Current Dependencies

### ISSUE THREAD

**Issue by burdisal** [isaacs/jackspeak#6]
Hello!

The dependencies for this package [listed on NPM](https://www.npmjs.com/package/jackspeak?activeTab=dependencies) do not match the actual dependencies declared in this package's `package.json`.

I discovered this with a new script I created to check my projects for the new [NPM "Manifest Confusion" attack](https://blog.vlt.sh/blog/the-massive-hole-in-the-npm-ecosystem), and this package gets flagged because of this.

**Comment by crrdean** [comment]
+1

**Comment by burdisal** [comment]
I have opened a feature request to check this using Github's Dependabot as well: dependabot/dependabot-core#7603

**Comment by isaacs** [comment]
package.json:

```
"dependencies": {
    "@isaacs/cliui": "^8.0.2"
  },
  ...
  "optionalDependencies": {
    "@pkgjs/parseargs": "^0.11.0"
  }
```

npmjs.com:

<img width="377" alt="Screenshot 2023-08-05 at 18 44 16" src="https://github.com/isaacs/jackspeak/assets/9287/0e5363ba-ffce-4833-9e57-4e5e6c23a770">

Seems to me that they match. Note that when npm parses a `package.json` file, `optionalDependencies` will be folded into `dependencies`, this semantic has been around since I first implemented `optionalDependencies` in npm.

Please report this as a bug to your flagging tool.

**Comment by isaacs** [comment]
Oh, you said it's a script you wrote. So report it to yourself I guess lol

You can get a more consistent view of how npm reads a package.json file by reading it using the `read-package-json` package. That would be a good way to ensure that you're actually seeing the manifest as npm sees it.
